"""검수 대기 판단 코퍼스용으로 고른 다국어 문맥이다."""

LANGUAGES = ("ko", "en", "ja")

# 항목마다 독립적으로 작성한 발화 family 하나이고, 번역문은 같은 family에 속한다.
DIRECT_FAMILIES = {
    "get_current_time": (
        ("time_now", {"ko": "지금 몇 시야?", "en": "What time is it right now?", "ja": "ただいまの時刻は何時ですか？"}, {"timezone": "local"}),
        ("time_local", {"ko": "현지 시각을 알려줘.", "en": "Tell me the local time.", "ja": "現地時刻を教えて。"}, {"timezone": "local"}),
        ("time_clock", {"ko": "시계에 지금 몇 시라고 나와?", "en": "What does the clock say at the moment?", "ja": "時計には今何時と表示されている？"}, {"timezone": "local"}),
        ("time_readout", {"ko": "현재 시간을 읽어 줘.", "en": "Read out the current time for me.", "ja": "現在時刻を読み上げて。"}, {"timezone": "local"}),
        ("time_check", {"ko": "시간 한번 확인해 줄래?", "en": "Could you do a quick time check?", "ja": "時刻をちょっと確認してくれる？"}, {"timezone": "local"}),
        ("time_wristwatch", {"ko": "손목시계 대신 여기서 시간을 확인하고 싶어.", "en": "I'd like to check the time here instead of looking at my watch.", "ja": "腕時計を見る代わりに、ここで時刻を確認したい。"}, {"timezone": "local"}),
        ("time_for_note", {"ko": "메모에 적을 현재 시각을 알려줘.", "en": "Give me the current time so I can put it in a note.", "ja": "メモに書くため、今の時刻を教えて。"}, {"timezone": "local"}),
        ("time_computer", {"ko": "이 컴퓨터에 설정된 시간을 보여 줘.", "en": "Show me the time set on this computer.", "ja": "このパソコンに設定されている時刻を見せて。"}, {"timezone": "local"}),
        ("time_exact", {"ko": "분까지 정확히 지금 시각을 말해 줘.", "en": "Tell me the exact time, down to the minute.", "ja": "分まで含めて正確な現在時刻を教えて。"}, {"timezone": "local"}),
        ("time_lost_track", {"ko": "일에 집중하느라 시간을 놓쳤어. 지금 몇 시야?", "en": "I lost track while working; what time is it now?", "ja": "作業に集中して時間を忘れていた。今何時？"}, {"timezone": "local"}),
        ("time_status", {"ko": "현재 시각이 어떻게 돼?", "en": "What's the current time?", "ja": "現在時刻は何時？"}, {"timezone": "local"}),
        ("time_display", {"ko": "현재 시간 표시를 확인해 줘.", "en": "Check the current time display.", "ja": "現在の時刻表示を確認して。"}, {"timezone": "local"}),
        ("time_tell", {"ko": "지금 시간을 말해 줘.", "en": "Tell me the time now.", "ja": "今の時間を教えて。"}, {"timezone": "local"}),
        ("time_timestamp", {"ko": "기록에 넣을 타임스탬프가 필요해. 지금 시각을 알려줘.", "en": "I need a timestamp for the log; what's the time now?", "ja": "記録に入れるタイムスタンプが必要です。今の時刻を教えて。"}, {"timezone": "local"}),
        ("time_clock_face", {"ko": "지금 시계 바늘이 가리키는 시간을 알려줘.", "en": "Tell me the time shown by the clock hands.", "ja": "時計の針が今示している時刻を教えて。"}, {"timezone": "local"}),
        ("time_watch", {"ko": "지금 시각 좀 봐 줘.", "en": "Would you check the time for me?", "ja": "今の時刻を見てくれる？"}, {"timezone": "local"}),
        ("time_brief", {"ko": "몇 시인지 궁금해.", "en": "I'm wondering what time it is.", "ja": "今何時なのか知りたい。"}, {"timezone": "local"}),
        ("time_voice", {"ko": "현재 시각을 음성으로 알려 줘.", "en": "Say the current time aloud.", "ja": "現在時刻を声で知らせて。"}, {"timezone": "local"}),
        ("time_screen", {"ko": "지금 몇 시인지 화면에 표시해 줘.", "en": "Display the current time on screen.", "ja": "今何時か画面に表示して。"}, {"timezone": "local"}),
        ("time_clock_read", {"ko": "벽시계가 가리키는 현재 시각을 확인해 줘.", "en": "Check the current time shown by the wall clock.", "ja": "壁時計が示す現在時刻を確認して。"}, {"timezone": "local"}),
        ("time_digital", {"ko": "디지털 시계 기준으로 지금 몇 시인지 알려줘.", "en": "Tell me the time according to the digital clock.", "ja": "デジタル時計で今何時か教えて。"}, {"timezone": "local"}),
        ("time_local_clock", {"ko": "여기 현지 시간으로 지금 몇 시인지 궁금해.", "en": "I want to know the time here locally.", "ja": "ここ現地の今の時刻を知りたい。"}, {"timezone": "local"}),
        ("time_moment", {"ko": "바로 이 순간의 시각을 알려 줘.", "en": "Give me the time at this very moment.", "ja": "まさに今この瞬間の時刻を教えて。"}, {"timezone": "local"}),
        ("time_how_late", {"ko": "지금 얼마나 늦었어?", "en": "How late is it now?", "ja": "今、何時くらい？"}, {"timezone": "local"}),
        ("time_begin", {"ko": "지금 시작할 수 있는 시간인지 시계를 확인해 줘.", "en": "Check the clock so I know whether it's time to start.", "ja": "始める時間かどうか、時計を確認して。"}, {"timezone": "local"}),
        ("time_log", {"ko": "작업 로그에 쓸 현재 시각을 확인하고 싶어.", "en": "I need the current time for a work log.", "ja": "作業ログに記す現在時刻を確認したい。"}, {"timezone": "local"}),
        ("time_clock_status", {"ko": "시계가 지금 맞는 시간을 표시하는지 읽어 줘.", "en": "Read the time the clock is showing right now.", "ja": "時計が今表示している時刻を読み取って。"}, {"timezone": "local"}),
        ("time_query", {"ko": "몇 시인지 바로 알려 줄 수 있어?", "en": "Can you tell me what time it is?", "ja": "今何時かすぐ教えてくれる？"}, {"timezone": "local"}),
        ("time_now_minutes", {"ko": "현재 몇 시 몇 분인지 알려줘.", "en": "What hour and minute is it right now?", "ja": "今は何時何分？"}, {"timezone": "local"}),
        ("time_clock_face_read", {"ko": "시계판을 보고 지금 시간을 알려줘.", "en": "Look at the clock face and tell me the time.", "ja": "文字盤を見て今の時刻を教えて。"}, {"timezone": "local"}),
        ("time_short_question", {"ko": "지금 시각은?", "en": "Time right now?", "ja": "今の時刻は？"}, {"timezone": "local"}),
        ("time_where", {"ko": "내가 있는 곳의 현지 시각이 몇 시야?", "en": "What's the local time where I am?", "ja": "私がいる場所の現地時刻は何時？"}, {"timezone": "local"}),
        ("time_remind_myself", {"ko": "잠깐 기록해 둘게. 현재 시각을 알려 줘.", "en": "I want to make a quick note; tell me the current time.", "ja": "少し記録しておきたいので、現在時刻を教えて。"}, {"timezone": "local"}),
        ("time_clock_reading", {"ko": "지금 시계 숫자가 어떻게 표시되는지 말해 줘.", "en": "Tell me the numbers displayed on the clock now.", "ja": "時計に今どんな数字が表示されているか教えて。"}, {"timezone": "local"}),
        ("time_check_now", {"ko": "시계 확인: 지금 몇 시야?", "en": "Quick check: what time is it?", "ja": "時刻を確認したい。今何時？"}, {"timezone": "local"}),
        ("time_at_hand", {"ko": "당장 현재 시각을 확인해 줘.", "en": "Please check the time at hand.", "ja": "ただいまの時刻を確認して。"}, {"timezone": "local"}),
        ("time_asking", {"ko": "시간 좀 알려 주실래요?", "en": "May I have the current time?", "ja": "今の時刻を教えていただけますか？"}, {"timezone": "local"}),
        ("time_local_readout", {"ko": "내 지역의 지금 시간을 읽어 줘.", "en": "Read the current time for my region.", "ja": "この地域の現在時刻を読み上げて。"}, {"timezone": "local"}),
        ("time_hour", {"ko": "지금 몇 시인지 알고 싶어.", "en": "I'd like to know what time it is now.", "ja": "今何時か知りたい。"}, {"timezone": "local"}),
        ("time_timestamp_now", {"ko": "현재 시각을 타임스탬프로 남길 수 있게 알려 줘.", "en": "Tell me the current time so I can record a timestamp.", "ja": "タイムスタンプを残せるよう、現在時刻を教えて。"}, {"timezone": "local"}),
        ("time_what_clock", {"ko": "현재 시계에는 몇 시라고 떠 있어?", "en": "What time is on the clock currently?", "ja": "今、時計には何時と出ている？"}, {"timezone": "local"}),
        ("time_read_clock", {"ko": "지금 시간을 한번 읽어 봐.", "en": "Read the clock for me now.", "ja": "今、時計を読んで。"}, {"timezone": "local"}),
        ("time_please", {"ko": "지금 시각 알려주면 고맙겠어.", "en": "I'd appreciate the current time.", "ja": "現在時刻を教えてもらえると助かる。"}, {"timezone": "local"}),
        ("time_watch_face", {"ko": "시계 화면에 뜬 현재 시간을 확인해 줘.", "en": "Check the current time on the clock display.", "ja": "時計の表示に出ている現在時刻を確認して。"}, {"timezone": "local"}),
        ("time_clock_value", {"ko": "지금 시간 값을 알려 줘.", "en": "What's the time value right now?", "ja": "今の時刻を教えて。"}, {"timezone": "local"}),
        ("time_local_now", {"ko": "현재 내 위치의 시간을 말해 줘.", "en": "Give me the time at my current location.", "ja": "今いる場所の時刻を教えて。"}, {"timezone": "local"}),
        ("time_right_now", {"ko": "바로 지금 시각이 몇 시야?", "en": "What is the time this second?", "ja": "まさに今は何時？"}, {"timezone": "local"}),
        ("time_check_clock", {"ko": "현재 시계 시간을 확인해 줘.", "en": "Check what time the clock reads.", "ja": "時計の時刻を確認して。"}, {"timezone": "local"}),
        ("time_current_reading", {"ko": "시계의 현재 읽기값을 알려줘.", "en": "Give me the clock's current reading.", "ja": "時計の現在の表示を教えて。"}, {"timezone": "local"}),
        ("time_time_please", {"ko": "지금 몇 시인지 부탁해.", "en": "The time, please?", "ja": "今何時かお願いします。"}, {"timezone": "local"}),
        ("time_clock_now", {"ko": "시계가 지금 가리키는 시각을 말해 줘.", "en": "What time is the clock pointing to now?", "ja": "時計が今指している時刻を教えて。"}, {"timezone": "local"}),
        ("time_current_clock", {"ko": "현재 시계가 몇 시를 가리키는지 알려 줘.", "en": "Tell me what time the clock is showing.", "ja": "時計が何時を示しているか教えて。"}, {"timezone": "local"}),
    ),
    "get_running_apps": (
        ("apps_open_now", {"ko": "지금 열려 있는 앱이 뭐야?", "en": "Which apps are open right now?", "ja": "今開いているアプリは何？"}, {"scope": "all_running_applications"}),
        ("apps_running_now", {"ko": "현재 실행 중인 프로그램을 나열해 줘.", "en": "List the programs currently running.", "ja": "現在実行中のプログラムを一覧にして。"}, {"scope": "all_running_applications"}),
        ("apps_show_list", {"ko": "켜져 있는 응용 프로그램 목록을 보여 줘.", "en": "Show me a list of active applications.", "ja": "起動中のアプリケーション一覧を見せて。"}, {"scope": "all_running_applications"}),
        ("apps_background", {"ko": "백그라운드에서 돌아가는 앱을 확인해 줘.", "en": "Check which apps are running in the background.", "ja": "バックグラウンドで動いているアプリを確認して。"}, {"scope": "all_running_applications"}),
        ("apps_computer", {"ko": "이 컴퓨터에서 실행 중인 앱이 어떤 건지 알려줘.", "en": "Tell me which apps are running on this computer.", "ja": "このパソコンで実行中のアプリを教えて。"}, {"scope": "all_running_applications"}),
        ("apps_processes", {"ko": "현재 살아 있는 앱 프로세스를 나열해 줘.", "en": "List the application processes that are active now.", "ja": "今動いているアプリのプロセスを一覧にして。"}, {"scope": "all_running_applications"}),
        ("apps_windows", {"ko": "열린 창과 프로그램을 목록으로 정리해 줘.", "en": "Make a list of the windows and programs I have open.", "ja": "開いているウィンドウとプログラムを一覧にして。"}, {"scope": "all_running_applications"}),
        ("apps_inventory", {"ko": "지금 켜 둔 소프트웨어를 전부 알려 줘.", "en": "Tell me all the software I currently have open.", "ja": "今開いているソフトを全部教えて。"}, {"scope": "all_running_applications"}),
        ("apps_active", {"ko": "활성 상태인 프로그램이 무엇인지 확인해 줘.", "en": "Find out which programs are active.", "ja": "アクティブなプログラムを調べて。"}, {"scope": "all_running_applications"}),
        ("apps_session", {"ko": "이 세션에서 아직 실행 중인 앱을 보여 줘.", "en": "Show the apps still running in this session.", "ja": "このセッションでまだ動いているアプリを見せて。"}, {"scope": "all_running_applications"}),
        ("apps_desktop", {"ko": "바탕화면에서 열려 있는 프로그램이 뭐가 있는지 확인해 줘.", "en": "Check what programs are open on the desktop.", "ja": "デスクトップで開いているプログラムを確認して。"}, {"scope": "all_running_applications"}),
        ("apps_windows_list", {"ko": "열려 있는 창 목록을 알려줘.", "en": "Give me the list of open windows.", "ja": "開いているウィンドウの一覧を教えて。"}, {"scope": "all_running_applications"}),
        ("apps_inventory_active", {"ko": "지금 실행 상태인 앱을 빠짐없이 보여 줘.", "en": "Show every app that is currently active.", "ja": "現在動作しているアプリを漏れなく見せて。"}, {"scope": "all_running_applications"}),
        ("apps_check_running", {"ko": "컴퓨터에서 뭐가 돌아가고 있는지 체크해 줘.", "en": "Check what's running on the computer.", "ja": "パソコンで何が動いているか確認して。"}, {"scope": "all_running_applications"}),
        ("apps_process_list", {"ko": "실행된 앱 프로세스 목록을 뽑아 줘.", "en": "Pull up the list of running app processes.", "ja": "実行中のアプリプロセス一覧を出して。"}, {"scope": "all_running_applications"}),
        ("apps_open_programs", {"ko": "내가 열어 둔 프로그램 이름을 알려줘.", "en": "Tell me the names of the programs I've left open.", "ja": "開いたままのプログラム名を教えて。"}, {"scope": "all_running_applications"}),
        ("apps_current_state", {"ko": "현재 앱 실행 상태를 확인하고 싶어.", "en": "I want to see the current app activity.", "ja": "現在のアプリの実行状況を確認したい。"}, {"scope": "all_running_applications"}),
        ("apps_what_open", {"ko": "내 PC에서 지금 어떤 앱이 열려 있는지 알려줘.", "en": "What's open on my PC at the moment?", "ja": "私のPCで今どのアプリが開いている？"}, {"scope": "all_running_applications"}),
        ("apps_active_software", {"ko": "활성화된 소프트웨어를 전부 나열해 줘.", "en": "Enumerate all the software that is active.", "ja": "起動しているソフトを全部挙げて。"}, {"scope": "all_running_applications"}),
        ("apps_background_inventory", {"ko": "뒤에서 실행 중인 앱까지 포함해서 목록을 만들어 줘.", "en": "Make a list that includes apps running behind the scenes.", "ja": "裏で動いているアプリも含めて一覧を作って。"}, {"scope": "all_running_applications"}),
        ("apps_open_programs_now", {"ko": "지금 켜져 있는 프로그램이 몇 개인지와 이름을 알려줘.", "en": "Tell me how many programs are open and what they are called.", "ja": "今開いているプログラムの数と名前を教えて。"}, {"scope": "all_running_applications"}),
        ("apps_running_inventory", {"ko": "실행 중인 응용 프로그램 현황을 보여 줘.", "en": "Show the current inventory of running applications.", "ja": "実行中のアプリケーションの状況を見せて。"}, {"scope": "all_running_applications"}),
        ("apps_application_state", {"ko": "현재 실행 상태인 앱 이름을 하나씩 말해 줘.", "en": "Name each application that's active right now.", "ja": "今動いているアプリの名前を一つずつ教えて。"}, {"scope": "all_running_applications"}),
        ("apps_status_overview", {"ko": "열려 있는 앱 현황을 한눈에 보여 줘.", "en": "Give me an overview of the apps that are open.", "ja": "開いているアプリの状況を一覧で見せて。"}, {"scope": "all_running_applications"}),
        ("apps_running_names", {"ko": "지금 돌아가는 프로그램 이름만 알려줘.", "en": "Just give me the names of the programs running now.", "ja": "今動いているプログラム名だけ教えて。"}, {"scope": "all_running_applications"}),
        ("apps_application_list", {"ko": "응용 프로그램 창에서 현재 사용 가능한 앱 목록을 보여 줘.", "en": "Show me the applications currently available in the app window.", "ja": "アプリのウィンドウにある現在利用中の一覧を見せて。"}, {"scope": "all_running_applications"}),
        ("apps_running_snapshot", {"ko": "실행 중인 앱 상태를 지금 스냅샷으로 보여 줘.", "en": "Give me a snapshot of the applications running now.", "ja": "今実行中のアプリの状態をスナップショットで見せて。"}, {"scope": "all_running_applications"}),
        ("apps_foreground_background", {"ko": "앞에 떠 있는 앱과 백그라운드 앱을 모두 나열해 줘.", "en": "List both the foreground apps and the background ones.", "ja": "前面のアプリとバックグラウンドのアプリを両方一覧にして。"}, {"scope": "all_running_applications"}),
        ("apps_desktop_session", {"ko": "현재 데스크톱 세션에서 열린 프로그램을 확인해 줘.", "en": "Check the programs open in the current desktop session.", "ja": "現在のデスクトップセッションで開いているプログラムを確認して。"}, {"scope": "all_running_applications"}),
        ("apps_whats_active", {"ko": "지금 활성화되어 있는 앱이 뭔지 궁금해.", "en": "I'm curious which apps are active right now.", "ja": "今アクティブなアプリが何か知りたい。"}, {"scope": "all_running_applications"}),
        ("apps_running_report", {"ko": "열려 있는 앱을 보고서처럼 정리해 줘.", "en": "Summarize the open applications in a short report.", "ja": "開いているアプリを短いレポートにまとめて。"}, {"scope": "all_running_applications"}),
        ("apps_list_running", {"ko": "현재 컴퓨터에서 동작하는 앱들을 목록으로 만들어 줘.", "en": "Create a list of the apps operating on this computer.", "ja": "このパソコンで動作中のアプリを一覧にして。"}, {"scope": "all_running_applications"}),
        ("apps_live_state", {"ko": "지금 실행되는 소프트웨어를 실시간으로 확인해 줘.", "en": "Show me the software running on the machine right now.", "ja": "このマシンで今実行されているソフトを見せて。"}, {"scope": "all_running_applications"}),
        ("apps_open_inventory", {"ko": "열린 앱이 무엇인지 하나도 빠뜨리지 말고 알려줘.", "en": "Don't leave any out; tell me which apps are open.", "ja": "漏れなく、開いているアプリを教えて。"}, {"scope": "all_running_applications"}),
        ("apps_current_processes", {"ko": "현재 실행 중인 사용자 앱을 보여 줘.", "en": "Show the user applications currently running.", "ja": "現在実行中のユーザーアプリを見せて。"}, {"scope": "all_running_applications"}),
        ("apps_open_state", {"ko": "지금 열려 있는 프로그램 상태를 알려줘.", "en": "Tell me the state of the programs that are open now.", "ja": "今開いているプログラムの状態を教えて。"}, {"scope": "all_running_applications"}),
        ("apps_running_checklist", {"ko": "실행 중인 프로그램을 체크리스트로 뽑아 줘.", "en": "Make a checklist of the programs that are running.", "ja": "実行中のプログラムをチェックリストにして。"}, {"scope": "all_running_applications"}),
        ("apps_whats_running", {"ko": "현재 백그라운드 포함 뭐가 실행 중이야?", "en": "What's running at the moment, including in the background?", "ja": "バックグラウンドも含めて、今何が動いている？"}, {"scope": "all_running_applications"}),
        ("apps_desktop_inventory", {"ko": "이 바탕화면에서 사용 중인 앱을 나열해 줘.", "en": "List the apps in use on this desktop.", "ja": "このデスクトップで使用中のアプリを一覧にして。"}, {"scope": "all_running_applications"}),
        ("apps_titles", {"ko": "현재 열려 있는 앱 창 제목을 알려줘.", "en": "Tell me the titles of the application windows currently open.", "ja": "現在開いているアプリウィンドウのタイトルを教えて。"}, {"scope": "all_running_applications"}),
        ("apps_session_status", {"ko": "이 PC에서 지금 실행되고 있는 프로그램 현황을 알려줘.", "en": "What's the current program activity on this PC?", "ja": "このPCで今実行中のプログラム状況を教えて。"}, {"scope": "all_running_applications"}),
        ("apps_active_list", {"ko": "현재 활성 프로그램들을 이름 순으로 보여 줘.", "en": "Show the active programs in a list by name.", "ja": "現在アクティブなプログラムを名前順に一覧表示して。"}, {"scope": "all_running_applications"}),
        ("apps_application_overview", {"ko": "지금 실행 상태인 애플리케이션을 요약해 줘.", "en": "Summarize which applications are currently active.", "ja": "現在動作中のアプリケーションをまとめて。"}, {"scope": "all_running_applications"}),
        ("apps_open_windows_count", {"ko": "열린 앱 창이 몇 개나 있는지 세고 목록도 보여 줘.", "en": "Count the open app windows and show me the list.", "ja": "開いているアプリウィンドウを数えて、一覧も見せて。"}, {"scope": "all_running_applications"}),
        ("apps_background_running", {"ko": "백그라운드에서 실행되고 있는 소프트웨어를 알려줘.", "en": "Which software is running in the background?", "ja": "バックグラウンドで実行中のソフトを教えて。"}, {"scope": "all_running_applications"}),
        ("apps_live_inventory", {"ko": "현재 열려 있는 프로그램 목록을 갱신해서 보여 줘.", "en": "Refresh and show the list of programs open now.", "ja": "現在開いているプログラムの一覧を更新して見せて。"}, {"scope": "all_running_applications"}),
        ("apps_active_windows", {"ko": "지금 활성 창에 해당하는 프로그램이 무엇인지 알려줘.", "en": "Tell me which programs correspond to the active windows.", "ja": "現在アクティブなウィンドウに対応するプログラムを教えて。"}, {"scope": "all_running_applications"}),
        ("apps_program_status", {"ko": "현재 실행 중인 프로그램을 확인하고 이름을 읽어 줘.", "en": "Check the programs running now and read their names.", "ja": "今実行中のプログラムを確認して、名前を読み上げて。"}, {"scope": "all_running_applications"}),
        ("apps_inventory_session", {"ko": "내 현재 세션에서 떠 있는 모든 앱을 확인해 줘.", "en": "Check every app that is active in my current session.", "ja": "現在のセッションで動いているアプリを全部確認して。"}, {"scope": "all_running_applications"}),
        ("apps_software_state", {"ko": "현재 열린 소프트웨어 창들을 목록으로 보고 싶어.", "en": "I'd like a list of the software windows currently open.", "ja": "現在開いているソフトウェアのウィンドウを一覧で見たい。"}, {"scope": "all_running_applications"}),
        ("apps_process_overview", {"ko": "활성화된 응용 프로그램들의 개요를 보여 줘.", "en": "Show an overview of the active applications.", "ja": "起動中のアプリケーションの概要を見せて。"}, {"scope": "all_running_applications"}),
    ),
    "take_screenshot": (
        ("screen_capture_now", {"ko": "지금 화면을 캡처해 줘.", "en": "Capture the screen now.", "ja": "今の画面をキャプチャして。"}, {"target": "current_display"}),
        ("screen_save", {"ko": "현재 디스플레이의 스크린샷을 저장해 줘.", "en": "Save a screenshot of the current display.", "ja": "現在のディスプレイのスクリーンショットを保存して。"}, {"target": "current_display"}),
        ("screen_evidence", {"ko": "지금 보이는 화면을 증거 이미지로 남겨 줘.", "en": "Keep an evidence image of what's visible on screen.", "ja": "画面に今見えている内容を証拠画像として残して。"}, {"target": "current_display"}),
        ("screen_note", {"ko": "메모에 붙일 수 있도록 화면을 한 장 찍어 줘.", "en": "Take a screen capture I can attach to my notes.", "ja": "メモに添付できるよう、画面を一枚撮って。"}, {"target": "current_display"}),
        ("screen_record", {"ko": "현재 데스크톱 모습을 이미지로 기록해 줘.", "en": "Record the desktop as an image in its current state.", "ja": "今のデスクトップの状態を画像として記録して。"}, {"target": "current_display"}),
        ("screen_before_change", {"ko": "다른 작업으로 넘어가기 전에 화면을 캡처해 둬.", "en": "Capture the screen before I move on to another task.", "ja": "別の作業に移る前に画面をキャプチャしておいて。"}, {"target": "current_display"}),
        ("screen_display_image", {"ko": "모니터에 표시된 내용을 현재 모습 그대로 이미지로 만들어 줘.", "en": "Make an image of exactly what is shown on the monitor.", "ja": "モニターに表示されている内容をそのまま画像にして。"}, {"target": "current_display"}),
        ("screen_bug_report", {"ko": "버그 보고서에 첨부할 현재 화면 캡처를 만들어 줘.", "en": "Create a capture of the current screen for a bug report.", "ja": "不具合報告に添付する現在の画面キャプチャを作って。"}, {"target": "current_display"}),
        ("screen_full_display", {"ko": "전체 화면을 한 장의 스크린샷으로 저장해 줘.", "en": "Save the whole display in a single screenshot.", "ja": "画面全体を一枚のスクリーンショットとして保存して。"}, {"target": "current_display"}),
        ("screen_current_view", {"ko": "지금 보고 있는 화면을 이미지로 남겨 줘.", "en": "Keep an image of the view I'm looking at right now.", "ja": "今見ている画面を画像で残して。"}, {"target": "current_display"}),
        ("screen_issue_attachment", {"ko": "이슈 티켓에 넣을 스크린샷을 지금 찍어 줘.", "en": "Take a screenshot now for the issue ticket.", "ja": "課題チケットに載せるスクリーンショットを今撮って。"}, {"target": "current_display"}),
        ("screen_work_state", {"ko": "작업 상태를 보존할 수 있게 바탕 화면을 캡처해 줘.", "en": "Capture the desktop so I can preserve the current work state.", "ja": "作業状態を残せるようにデスクトップをキャプチャして。"}, {"target": "current_display"}),
        ("screen_visual_record", {"ko": "현재 화면을 시각 기록으로 저장해 줘.", "en": "Save the current screen as a visual record.", "ja": "現在の画面を視覚的な記録として保存して。"}, {"target": "current_display"}),
        ("screen_snapshot", {"ko": "지금 데스크톱 스냅샷 하나 남겨 줘.", "en": "Take a snapshot of the desktop as it is now.", "ja": "今のデスクトップのスナップショットを撮って。"}, {"target": "current_display"}),
        ("screen_report", {"ko": "진행 보고서에 넣을 화면 이미지를 만들어 줘.", "en": "Make a screen image for the progress report.", "ja": "進捗報告に載せる画面画像を作って。"}, {"target": "current_display"}),
        ("screen_proof", {"ko": "현재 보이는 내용을 나중에 확인하도록 캡처해 줘.", "en": "Capture what is visible so I can refer back to it later.", "ja": "後で見返せるよう、今見えている内容をキャプチャして。"}, {"target": "current_display"}),
        ("screen_share_record", {"ko": "화면 공유 전에 지금 디스플레이를 캡처해 줘.", "en": "Capture the display before I share my screen.", "ja": "画面を共有する前に、今のディスプレイをキャプチャして。"}, {"target": "current_display"}),
        ("screen_support_ticket", {"ko": "지원 요청에 첨부할 수 있게 화면을 이미지로 저장해 줘.", "en": "Save an image of the screen that I can attach to a support request.", "ja": "サポート依頼に添付できるよう画面を画像で保存して。"}, {"target": "current_display"}),
        ("screen_current_desktop", {"ko": "지금 바탕화면을 캡처해서 파일로 남겨 줘.", "en": "Capture my desktop now and keep it as a file.", "ja": "今のデスクトップをキャプチャしてファイルに残して。"}, {"target": "current_display"}),
        ("screen_evidence_copy", {"ko": "현재 화면의 증거용 사본을 만들어 줘.", "en": "Make an evidence copy of the screen as it currently appears.", "ja": "現在の画面の証拠用コピーを作って。"}, {"target": "current_display"}),
        ("screen_workspace", {"ko": "열어 둔 작업 공간을 스크린샷으로 보관해 줘.", "en": "Keep a screenshot of the workspace I have open.", "ja": "開いている作業スペースをスクリーンショットで保存して。"}, {"target": "current_display"}),
        ("screen_attachment", {"ko": "현재 디스플레이 화면을 첨부 이미지로 캡처해 줘.", "en": "Capture the current display as an attachment image.", "ja": "現在のディスプレイを添付用の画像としてキャプチャして。"}, {"target": "current_display"}),
        ("screen_snapshot_note", {"ko": "작업 기록용으로 모니터 화면을 스냅샷해 줘.", "en": "Take a monitor snapshot for my work log.", "ja": "作業ログ用にモニター画面をスナップショットして。"}, {"target": "current_display"}),
        ("screen_capture_visible", {"ko": "현재 눈에 보이는 전체 화면을 찍어 줘.", "en": "Take a picture of the entire visible screen.", "ja": "今見えている画面全体を撮って。"}, {"target": "current_display"}),
        ("screen_document", {"ko": "지금 디스플레이 내용을 문서화하도록 캡처해 줘.", "en": "Capture the display to document what is on it now.", "ja": "今ディスプレイに表示されている内容を記録するためキャプチャして。"}, {"target": "current_display"}),
        ("screen_archive", {"ko": "현재 화면을 나중에 볼 수 있게 한 장 저장해 줘.", "en": "Save one image of the current screen for later.", "ja": "後で見られるように、現在の画面を一枚保存して。"}, {"target": "current_display"}),
        ("screen_visual_evidence", {"ko": "화면에 보이는 상태를 증거로 캡처해 줘.", "en": "Capture the visible state as evidence.", "ja": "画面に見えている状態を証拠としてキャプチャして。"}, {"target": "current_display"}),
        ("screen_save_view", {"ko": "지금 내 작업 화면을 이미지 파일로 보관해 줘.", "en": "Keep my current work view as an image file.", "ja": "今の作業画面を画像ファイルとして保存して。"}, {"target": "current_display"}),
        ("screen_capture_workspace", {"ko": "현재 워크스페이스를 화면 캡처로 남겨 줘.", "en": "Keep a screen capture of the current workspace.", "ja": "現在のワークスペースを画面キャプチャで残して。"}, {"target": "current_display"}),
        ("screen_record_state", {"ko": "모니터에 떠 있는 상태를 그대로 캡처해 줘.", "en": "Capture the state currently displayed on the monitor.", "ja": "モニターに表示中の状態をそのままキャプチャして。"}, {"target": "current_display"}),
        ("screen_full_snapshot", {"ko": "전체 디스플레이의 현재 모습을 한 번 저장해 줘.", "en": "Save one image of the entire display as it appears now.", "ja": "ディスプレイ全体の今の状態を一度保存して。"}, {"target": "current_display"}),
        ("screen_current_image", {"ko": "화면에 보이는 것을 이미지로 캡처해 줘.", "en": "Capture what is visible on screen as an image.", "ja": "画面に見えているものを画像としてキャプチャして。"}, {"target": "current_display"}),
        ("screen_bug_evidence", {"ko": "오류가 난 순간의 화면을 증거로 저장해 줘.", "en": "Save the screen as evidence of the error state.", "ja": "エラーが起きている画面を証拠として保存して。"}, {"target": "current_display"}),
        ("screen_current_frame", {"ko": "현재 화면 프레임을 한 장 이미지로 남겨 줘.", "en": "Keep a still image of the current screen frame.", "ja": "現在の画面を一枚の静止画像にして残して。"}, {"target": "current_display"}),
        ("screen_proof_note", {"ko": "메모에 붙일 현재 화면 증거를 캡처해 줘.", "en": "Capture proof of the current screen for my notes.", "ja": "メモ用に現在の画面の証拠をキャプチャして。"}, {"target": "current_display"}),
        ("screen_capture_record", {"ko": "지금 보이는 화면을 기록 이미지로 보존해 줘.", "en": "Preserve the screen as a record image of what is visible now.", "ja": "今見えている画面を記録画像として保存して。"}, {"target": "current_display"}),
        ("screen_one_shot", {"ko": "바탕 화면을 한 번만 캡처해서 남겨 줘.", "en": "Take a single capture of the desktop and keep it.", "ja": "デスクトップを一度だけキャプチャして残して。"}, {"target": "current_display"}),
        ("screen_ticket_proof", {"ko": "티켓에 붙일 수 있도록 현재 화면을 찍어 줘.", "en": "Take the current screen so I can attach it to the ticket.", "ja": "チケットに添付できるよう、現在の画面を撮って。"}, {"target": "current_display"}),
        ("screen_session_record", {"ko": "이 세션의 현재 화면을 이미지로 남겨 줘.", "en": "Save an image of the current screen for this session.", "ja": "このセッションの現在の画面を画像で残して。"}, {"target": "current_display"}),
        ("screen_current_copy", {"ko": "현재 데스크톱 화면의 사본을 이미지로 저장해 줘.", "en": "Save an image copy of the current desktop screen.", "ja": "現在のデスクトップ画面のコピーを画像で保存して。"}, {"target": "current_display"}),
        ("screen_display_capture", {"ko": "디스플레이에 지금 나타난 내용을 캡처 파일로 만들어 줘.", "en": "Make a capture file of what is displayed right now.", "ja": "今表示されている内容のキャプチャファイルを作って。"}, {"target": "current_display"}),
        ("screen_preserve", {"ko": "현재 보이는 작업 화면을 보존할 이미지로 남겨 줘.", "en": "Keep an image that preserves the work view I can see now.", "ja": "今見えている作業画面を保存用の画像として残して。"}, {"target": "current_display"}),
        ("screen_evidence_file", {"ko": "지금 모니터에 표시된 화면을 증거 파일로 캡처해 줘.", "en": "Capture the monitor display now as an evidence file.", "ja": "今モニターに表示されている画面を証拠ファイルとしてキャプチャして。"}, {"target": "current_display"}),
        ("screen_snapshot_current", {"ko": "현재 화면을 스냅샷 이미지로 저장해 둬.", "en": "Save a snapshot image of the screen as it is now.", "ja": "今の画面をスナップショット画像として保存しておいて。"}, {"target": "current_display"}),
        ("screen_capture_reference", {"ko": "나중에 참고하도록 현재 화면을 캡처해 줘.", "en": "Capture the current screen so I can use it as a reference later.", "ja": "後で参考にできるよう、現在の画面をキャプチャして。"}, {"target": "current_display"}),
        ("screen_display_record", {"ko": "지금 디스플레이에 나온 화면을 기록으로 남겨 줘.", "en": "Keep a record of the screen displayed right now.", "ja": "今ディスプレイに出ている画面を記録として残して。"}, {"target": "current_display"}),
        ("screen_desktop_image", {"ko": "현재 데스크톱을 이미지 한 장으로 만들어 줘.", "en": "Make a single image of the current desktop.", "ja": "現在のデスクトップを一枚の画像にして。"}, {"target": "current_display"}),
        ("screen_save_capture", {"ko": "현재 화면 캡처를 파일로 저장해 줘.", "en": "Save the current screen capture to a file.", "ja": "現在の画面キャプチャをファイルに保存して。"}, {"target": "current_display"}),
        ("screen_ask_capture", {"ko": "지금 보이는 화면을 스크린샷 한 장으로 남겨 줄래?", "en": "Could you leave me with one screenshot of what's visible right now?", "ja": "今見えている画面をスクリーンショット一枚に残してくれる？"}, {"target": "current_display"}),
        ("screen_still_image", {"ko": "현재 화면을 정지 이미지로 떠 줘.", "en": "Save a still of the current display.", "ja": "現在の画面を静止画像として保存して。"}, {"target": "current_display"}),
    ),
    "adjust_volume": (
        ("vol_01", {"ko": "시스템 음량을 10퍼센트 낮춰 줘.", "en": "Lower the system volume by ten percent.", "ja": "システム音量を10パーセント下げて。"}, {"direction": "down", "amount_percent": 10}),
        ("vol_02", {"ko": "스피커 소리를 15퍼센트 올려 줘.", "en": "Raise the speaker volume by fifteen percent.", "ja": "スピーカーの音量を15パーセント上げて。"}, {"direction": "up", "amount_percent": 15}),
        ("vol_03", {"ko": "재생 음량을 20퍼센트 줄여 줘.", "en": "Reduce the playback volume by twenty percent.", "ja": "再生音量を20パーセント下げて。"}, {"direction": "down", "amount_percent": 20}),
        ("vol_04", {"ko": "오디오 출력을 12퍼센트 높여 줘.", "en": "Increase the audio output by twelve percent.", "ja": "音声出力を12パーセント上げて。"}, {"direction": "up", "amount_percent": 12}),
        ("vol_05", {"ko": "컴퓨터 소리를 8퍼센트 낮춰 줘.", "en": "Turn the computer sound down by eight percent.", "ja": "パソコンの音を8パーセント下げて。"}, {"direction": "down", "amount_percent": 8}),
        ("vol_06", {"ko": "미디어 볼륨을 25퍼센트 키워 줘.", "en": "Boost the media volume by twenty-five percent.", "ja": "メディア音量を25パーセント上げて。"}, {"direction": "up", "amount_percent": 25}),
        ("vol_07", {"ko": "현재 볼륨에서 5퍼센트만 줄여 줘.", "en": "Take just five percent off the current volume.", "ja": "現在の音量から5パーセントだけ下げて。"}, {"direction": "down", "amount_percent": 5}),
        ("vol_08", {"ko": "헤드폰 출력 레벨을 18퍼센트 올려 줘.", "en": "Raise the headphone output level by eighteen percent.", "ja": "ヘッドホンの出力レベルを18パーセント上げて。"}, {"direction": "up", "amount_percent": 18}),
        ("vol_09", {"ko": "시스템 사운드 레벨을 14퍼센트 낮춰 줘.", "en": "Bring the system sound level down by fourteen percent.", "ja": "システムのサウンドレベルを14パーセント下げて。"}, {"direction": "down", "amount_percent": 14}),
        ("vol_10", {"ko": "영상 소리가 잘 들리게 출력 음량을 22퍼센트 높여 줘.", "en": "Raise the output volume by twenty-two percent so the video is easier to hear.", "ja": "動画を聞き取りやすくするため、出力音量を22パーセント上げて。"}, {"direction": "up", "amount_percent": 22}),
        ("vol_11", {"ko": "배경 음악이 너무 커. 재생 레벨을 17퍼센트 낮춰 줘.", "en": "The background music is too loud; lower playback by seventeen percent.", "ja": "BGMが大きすぎるので、再生レベルを17パーセント下げて。"}, {"direction": "down", "amount_percent": 17}),
        ("vol_12", {"ko": "내레이션이 안 들려서 스피커 음량을 11퍼센트 올려 줘.", "en": "I can't hear the narration; turn the speaker volume up by eleven percent.", "ja": "ナレーションが聞こえないので、スピーカー音量を11パーセント上げて。"}, {"direction": "up", "amount_percent": 11}),
        ("vol_13", {"ko": "재생 장치 음량을 30퍼센트 낮춰 줘.", "en": "Decrease the playback device volume by thirty percent.", "ja": "再生デバイスの音量を30パーセント下げて。"}, {"direction": "down", "amount_percent": 30}),
        ("vol_14", {"ko": "오디오 레벨을 28퍼센트 높여 줘.", "en": "Move the audio level up by twenty-eight percent.", "ja": "オーディオレベルを28パーセント上げて。"}, {"direction": "up", "amount_percent": 28}),
        ("vol_15", {"ko": "소리가 거슬리니까 마스터 볼륨을 9퍼센트 줄여 줘.", "en": "The sound is distracting; reduce master volume by nine percent.", "ja": "音が気になるので、マスター音量を9パーセント下げて。"}, {"direction": "down", "amount_percent": 9}),
        ("vol_16", {"ko": "회의에 맞게 전체 음량을 16퍼센트 높여 줘.", "en": "Raise the overall volume by sixteen percent for the meeting.", "ja": "会議に合わせて全体の音量を16パーセント上げて。"}, {"direction": "up", "amount_percent": 16}),
        ("vol_17", {"ko": "알림 소리가 너무 커서 시스템 볼륨을 13퍼센트 낮춰 줘.", "en": "The alerts are too loud, so lower system volume by thirteen percent.", "ja": "通知音が大きすぎるので、システム音量を13パーセント下げて。"}, {"direction": "down", "amount_percent": 13}),
        ("vol_18", {"ko": "음악을 더 잘 들을 수 있도록 재생 음량을 24퍼센트 올려 줘.", "en": "Raise playback volume by twenty-four percent so I can hear the music better.", "ja": "音楽をもっとよく聞けるよう、再生音量を24パーセント上げて。"}, {"direction": "up", "amount_percent": 24}),
        ("vol_19", {"ko": "스피커 출력을 19퍼센트 낮춰 줘.", "en": "Lower the speaker output by nineteen percent.", "ja": "スピーカー出力を19パーセント下げて。"}, {"direction": "down", "amount_percent": 19}),
        ("vol_20", {"ko": "현재 오디오를 21퍼센트 더 크게 설정해 줘.", "en": "Set the current audio twenty-one percent louder.", "ja": "現在のオーディオを21パーセント大きく設定して。"}, {"direction": "up", "amount_percent": 21}),
        ("vol_21", {"ko": "재생 장치의 레벨을 23퍼센트 줄여 줘.", "en": "Cut the playback device level by twenty-three percent.", "ja": "再生デバイスのレベルを23パーセント下げて。"}, {"direction": "down", "amount_percent": 23}),
        ("vol_22", {"ko": "시스템 오디오를 26퍼센트 올려 줘.", "en": "Turn system audio up by twenty-six percent.", "ja": "システムオーディオを26パーセント上げて。"}, {"direction": "up", "amount_percent": 26}),
        ("vol_23", {"ko": "영화 소리를 낮추게 볼륨을 7퍼센트 내려 줘.", "en": "Bring the volume down seven percent for the movie.", "ja": "映画の音を抑えるため、音量を7パーセント下げて。"}, {"direction": "down", "amount_percent": 7}),
        ("vol_24", {"ko": "통화 음성이 선명하게 들리도록 출력 음량을 32퍼센트 높여 줘.", "en": "Increase the output volume by thirty-two percent so the call is clear.", "ja": "通話の声がはっきり聞こえるよう、出力音量を32パーセント上げて。"}, {"direction": "up", "amount_percent": 32}),
        ("vol_25", {"ko": "컴퓨터의 마스터 레벨을 6퍼센트 낮춰 줘.", "en": "Lower the computer's master level by six percent.", "ja": "パソコンのマスターレベルを6パーセント下げて。"}, {"direction": "down", "amount_percent": 6}),
        ("vol_26", {"ko": "출력 사운드를 31퍼센트 키워 줘.", "en": "Boost the output sound by thirty-one percent.", "ja": "出力音声を31パーセント上げて。"}, {"direction": "up", "amount_percent": 31}),
        ("vol_27", {"ko": "배경 오디오를 줄이게 음량을 27퍼센트 낮춰 줘.", "en": "Reduce the volume by twenty-seven percent to soften the background audio.", "ja": "背景音を小さくするため、音量を27パーセント下げて。"}, {"direction": "down", "amount_percent": 27}),
        ("vol_28", {"ko": "전체 출력 레벨을 35퍼센트 올려 줘.", "en": "Raise the overall output level by thirty-five percent.", "ja": "全体の出力レベルを35パーセント上げて。"}, {"direction": "up", "amount_percent": 35}),
        ("vol_29", {"ko": "스피커 음량을 12퍼센트만 줄이면 돼.", "en": "Just reduce the speaker volume by twelve percent.", "ja": "スピーカー音量を12パーセントだけ下げればいい。"}, {"direction": "down", "amount_percent": 12}),
        ("vol_30", {"ko": "시스템 볼륨을 33퍼센트 높여 줘.", "en": "Set the system volume thirty-three percent higher.", "ja": "システム音量を33パーセント上げて。"}, {"direction": "up", "amount_percent": 33}),
        ("vol_31", {"ko": "헤드폰 소리를 29퍼센트 낮춰 줘.", "en": "Turn the headphones down by twenty-nine percent.", "ja": "ヘッドホンの音を29パーセント下げて。"}, {"direction": "down", "amount_percent": 29}),
        ("vol_32", {"ko": "음성 재생이 작게 들리니 레벨을 37퍼센트 높여 줘.", "en": "The voice playback is quiet; raise its level by thirty-seven percent.", "ja": "音声再生が小さいので、レベルを37パーセント上げて。"}, {"direction": "up", "amount_percent": 37}),
        ("vol_33", {"ko": "스피커 레벨을 18퍼센트 줄여 줘.", "en": "Take the speaker level down by eighteen percent.", "ja": "スピーカーレベルを18パーセント下げて。"}, {"direction": "down", "amount_percent": 18}),
        ("vol_34", {"ko": "미디어 출력을 38퍼센트 키워 줘.", "en": "Increase media output by thirty-eight percent.", "ja": "メディア出力を38パーセント上げて。"}, {"direction": "up", "amount_percent": 38}),
        ("vol_35", {"ko": "알림음 때문에 전체 음량을 4퍼센트만 낮춰 줘.", "en": "Lower the overall volume by just four percent because of the alerts.", "ja": "通知音が気になるので、全体の音量を4パーセントだけ下げて。"}, {"direction": "down", "amount_percent": 4}),
        ("vol_36", {"ko": "출력 장치의 소리를 41퍼센트 더 키워 줘.", "en": "Turn the audio output up by forty-one percent.", "ja": "オーディオ出力を41パーセント高くして。"}, {"direction": "up", "amount_percent": 41}),
        ("vol_37", {"ko": "재생 음량을 36퍼센트 낮추면 좋겠어.", "en": "I'd like the playback volume thirty-six percent lower.", "ja": "再生音量を36パーセント下げてほしい。"}, {"direction": "down", "amount_percent": 36}),
        ("vol_38", {"ko": "현재 소리를 42퍼센트 올려 줘.", "en": "Raise the current sound level by forty-two percent.", "ja": "現在の音量を42パーセント上げて。"}, {"direction": "up", "amount_percent": 42}),
        ("vol_39", {"ko": "마스터 볼륨을 39퍼센트 줄여 줘.", "en": "Reduce master volume by thirty-nine percent.", "ja": "マスター音量を39パーセント下げて。"}, {"direction": "down", "amount_percent": 39}),
        ("vol_40", {"ko": "컴퓨터 오디오 레벨을 44퍼센트 올려 줘.", "en": "Bring the computer audio level up by forty-four percent.", "ja": "パソコンのオーディオレベルを44パーセント上げて。"}, {"direction": "up", "amount_percent": 44}),
        ("vol_41", {"ko": "재생 볼륨을 43퍼센트 낮춰 줘.", "en": "Set playback volume forty-three percent lower.", "ja": "再生音量を43パーセント低くして。"}, {"direction": "down", "amount_percent": 43}),
        ("vol_42", {"ko": "스피커 출력을 45퍼센트 높여 줘.", "en": "Raise speaker output by forty-five percent.", "ja": "スピーカー出力を45パーセント上げて。"}, {"direction": "up", "amount_percent": 45}),
        ("vol_43", {"ko": "시스템 사운드를 46퍼센트 줄여 줘.", "en": "Turn system sound down by forty-six percent.", "ja": "システム音を46パーセント下げて。"}, {"direction": "down", "amount_percent": 46}),
        ("vol_44", {"ko": "오디오 출력을 47퍼센트 더 크게 만들어 줘.", "en": "Move the audio level up forty-seven percent.", "ja": "オーディオレベルを47パーセント大きくして。"}, {"direction": "up", "amount_percent": 47}),
        ("vol_45", {"ko": "볼륨을 48퍼센트 낮춰 줘.", "en": "Lower the volume by forty-eight percent.", "ja": "音量を48パーセント下げて。"}, {"direction": "down", "amount_percent": 48}),
        ("vol_46", {"ko": "재생 장치 소리를 49퍼센트 올려 줘.", "en": "Turn the playback device sound up by forty-nine percent.", "ja": "再生デバイスの音を49パーセント上げて。"}, {"direction": "up", "amount_percent": 49}),
        ("vol_47", {"ko": "출력 음량을 11퍼센트 낮춰 줘.", "en": "Drop the output volume by eleven percent.", "ja": "出力音量を11パーセント下げて。"}, {"direction": "down", "amount_percent": 11}),
        ("vol_48", {"ko": "미디어 사운드를 40퍼센트 키워 줘.", "en": "Boost media sound by forty percent.", "ja": "メディアの音を40パーセント上げて。"}, {"direction": "up", "amount_percent": 40}),
        ("vol_49", {"ko": "전체 음량을 34퍼센트 낮춰 줘.", "en": "Reduce the overall volume by thirty-four percent.", "ja": "全体の音量を34パーセント下げて。"}, {"direction": "down", "amount_percent": 34}),
        ("vol_50", {"ko": "시스템 출력을 26퍼센트 높여 줘.", "en": "Increase system output by twenty-six percent.", "ja": "システム出力を26パーセント上げて。"}, {"direction": "up", "amount_percent": 26}),
    ),
}

# Tier B 예시는 해당 해석기가 배포되기 전까지 대화 경로 전용으로 둔다.
TIER_B = (
    ("get_weather", "seoul_today", {"ko": "오늘 서울 날씨 알려줘.", "en": "What's the weather in Seoul today?", "ja": "今日のソウルの天気を教えて。"}, {"location": "Seoul"}),
    ("get_weather", "busan_tomorrow", {"ko": "내일 부산에 비 올지 확인해 줘.", "en": "Check whether it will rain in Busan tomorrow.", "ja": "明日の釜山は雨が降るか確認して。"}, {"location": "Busan", "date": "tomorrow"}),
    ("get_weather", "tokyo_temperature", {"ko": "도쿄 지금 기온이 몇 도야?", "en": "How warm is it in Tokyo right now?", "ja": "今の東京の気温は何度？"}, {"location": "Tokyo"}),
    ("get_weather", "jeju_weekend", {"ko": "이번 주말 제주도 예보 좀 봐줘.", "en": "Look up the forecast for Jeju this weekend.", "ja": "今週末の済州島の予報を調べて。"}, {"location": "Jeju", "date": "weekend"}),
    ("get_weather", "incheon_wind", {"ko": "인천 바람이 얼마나 부는지 알려줘.", "en": "Tell me how windy it is in Incheon.", "ja": "仁川の風の強さを教えて。"}, {"location": "Incheon"}),
    ("get_weather", "dawn_snow", {"ko": "내일 새벽 강릉에 눈 예보 있어?", "en": "Is snow expected in Gangneung early tomorrow?", "ja": "明日の早朝、江陵に雪の予報はある？"}, {"location": "Gangneung", "date": "tomorrow"}),
    ("get_weather", "daegu_humidity", {"ko": "대구 습도 확인해 줄래?", "en": "Could you check the humidity in Daegu?", "ja": "大邱の湿度を確認してくれる？"}, {"location": "Daegu"}),
    ("get_weather", "daejeon_evening", {"ko": "오늘 저녁 대전 날씨 어때?", "en": "What's the weather like in Daejeon this evening?", "ja": "今夜の大田の天気はどう？"}, {"location": "Daejeon", "date": "today_evening"}),
    ("get_weather", "gwangju_rain", {"ko": "광주에 지금 비가 오는지 알아봐 줘.", "en": "Find out if it's raining in Gwangju now.", "ja": "今、光州で雨が降っているか調べて。"}, {"location": "Gwangju"}),
    ("get_weather", "suwon_week", {"ko": "수원 이번 주 기온 추이를 보여 줘.", "en": "Show me this week's temperature outlook for Suwon.", "ja": "水原の今週の気温の見通しを見せて。"}, {"location": "Suwon", "date": "week"}),
    ("get_weather", "weather_umbrella", {"ko": "오늘 서울 나갈 때 우산 챙겨야 할까?", "en": "Do I need an umbrella when I go out in Seoul today?", "ja": "今日ソウルに出かけるなら傘が必要？"}, {"location": "Seoul", "date": "today"}),
    ("get_weather", "weather_clothing", {"ko": "내일 부산에 뭘 입고 가면 좋을지 날씨 기준으로 알려줘.", "en": "Based on tomorrow's weather, what should I wear in Busan?", "ja": "明日の釜山の天気に合わせるなら、何を着るとよさそう？"}, {"location": "Busan", "date": "tomorrow"}),
    ("set_timer", "timer_five", {"ko": "5분 타이머 맞춰 줘.", "en": "Set a timer for five minutes.", "ja": "5分のタイマーをセットして。"}, {"duration_minutes": 5}),
    ("set_timer", "timer_ten_tea", {"ko": "차 우릴 동안 10분 타이머 시작해 줘.", "en": "Start a ten-minute timer for the tea.", "ja": "お茶を蒸らす間、10分のタイマーを始めて。"}, {"duration_minutes": 10, "label": "tea"}),
    ("set_timer", "timer_quarter", {"ko": "15분 뒤에 울리도록 타이머 설정해 줘.", "en": "Set a timer to ring in fifteen minutes.", "ja": "15分後に鳴るタイマーを設定して。"}, {"duration_minutes": 15}),
    ("set_timer", "timer_pasta", {"ko": "파스타 삶는 데 8분 타이머 걸어 줘.", "en": "Put on an eight-minute timer for the pasta.", "ja": "パスタをゆでるために8分のタイマーをかけて。"}, {"duration_minutes": 8, "label": "pasta"}),
    ("set_timer", "timer_break", {"ko": "25분 집중하고 쉴 수 있게 타이머 맞춰 줘.", "en": "Set a timer so I can focus for twenty-five minutes before a break.", "ja": "25分集中してから休憩できるようにタイマーを設定して。"}, {"duration_minutes": 25, "label": "focus"}),
    ("set_timer", "timer_half_hour", {"ko": "30분 타이머 부탁해.", "en": "I'd like a thirty-minute timer, please.", "ja": "30分のタイマーをお願いします。"}, {"duration_minutes": 30}),
    ("set_timer", "timer_eggs", {"ko": "달걀 반숙으로 삶게 7분 재 줘.", "en": "Time seven minutes for soft-boiled eggs.", "ja": "半熟卵を作るので7分を計って。"}, {"duration_minutes": 7, "label": "eggs"}),
    ("set_timer", "timer_nap", {"ko": "낮잠은 40분만 잘게. 알람 타이머 걸어 줘.", "en": "I'm taking a forty-minute nap; set a timer to wake me.", "ja": "40分だけ昼寝するので、起きるためのタイマーをかけて。"}, {"duration_minutes": 40, "label": "nap"}),
    ("set_timer", "timer_hour", {"ko": "한 시간 뒤에 알려 주는 타이머를 켜 줘.", "en": "Start a timer that will alert me in an hour.", "ja": "1時間後に知らせるタイマーを開始して。"}, {"duration_minutes": 60}),
    ("set_timer", "timer_microwave", {"ko": "전자레인지에 넣은 음식 때문에 2분 타이머 맞춰.", "en": "Set a two-minute timer for the food in the microwave.", "ja": "電子レンジの中の食べ物用に2分のタイマーを設定して。"}, {"duration_minutes": 2, "label": "microwave"}),
    ("set_timer", "timer_stretch", {"ko": "5분 스트레칭할 수 있게 시간을 재 줘.", "en": "Time a five-minute stretch break for me.", "ja": "5分間ストレッチできるよう時間を計って。"}, {"duration_minutes": 5, "label": "stretch"}),
    ("set_timer", "timer_minutes", {"ko": "20분 후에 소리 나게 타이머 해 둬.", "en": "Have a timer go off in twenty minutes.", "ja": "20分後に音が鳴るようタイマーをかけて。"}, {"duration_minutes": 20}),
    ("cancel_timer", "cancel_active", {"ko": "지금 돌아가는 타이머 취소해 줘.", "en": "Cancel the timer that's running now.", "ja": "今動いているタイマーをキャンセルして。"}, {"target": "active"}),
    ("cancel_timer", "cancel_tea", {"ko": "차 타이머는 이제 필요 없어. 꺼 줘.", "en": "I don't need the tea timer anymore; stop it.", "ja": "お茶のタイマーはもういらないので止めて。"}, {"label": "tea"}),
    ("cancel_timer", "cancel_all", {"ko": "예약된 타이머 전부 취소해 줘.", "en": "Cancel all the timers I have set.", "ja": "設定してあるタイマーを全部キャンセルして。"}, {"target": "all"}),
    ("cancel_timer", "cancel_pasta", {"ko": "파스타 타이머를 잘못 맞췄어. 그거 취소해.", "en": "I set the pasta timer by mistake; cancel that one.", "ja": "パスタのタイマーを間違えて設定したので、それを取り消して。"}, {"label": "pasta"}),
    ("cancel_timer", "cancel_old", {"ko": "먼저 걸어 둔 타이머만 지워 줘.", "en": "Remove only the timer I started earlier.", "ja": "先にかけたタイマーだけ消して。"}, {"target": "earlier"}),
    ("cancel_timer", "cancel_nap", {"ko": "낮잠 타이머 멈춰 줘. 이미 일어났어.", "en": "Stop the nap timer; I'm already awake.", "ja": "昼寝のタイマーを止めて。もう起きたよ。"}, {"label": "nap"}),
    ("cancel_timer", "cancel_kitchen", {"ko": "주방에서 울리는 타이머 꺼 줘.", "en": "Turn off the timer ringing in the kitchen.", "ja": "キッチンで鳴っているタイマーを止めて。"}, {"target": "ringing"}),
    ("cancel_timer", "cancel_focus", {"ko": "집중 시간 타이머는 취소할게.", "en": "Cancel the focus-session timer.", "ja": "集中時間のタイマーをキャンセルして。"}, {"label": "focus"}),
    ("cancel_timer", "cancel_short", {"ko": "방금 시작한 짧은 타이머 중단해 줘.", "en": "Stop the short timer I just started.", "ja": "さっき始めた短いタイマーを止めて。"}, {"target": "latest"}),
    ("cancel_timer", "cancel_microwave", {"ko": "전자레인지 타이머 소리 끄고 취소해 줘.", "en": "Silence and cancel the microwave timer.", "ja": "電子レンジのタイマー音を止めて、タイマーを取り消して。"}, {"label": "microwave"}),
    ("cancel_timer", "cancel_everything", {"ko": "걸려 있는 카운트다운 더는 필요 없으니 다 지워.", "en": "I don't need any of the countdowns, so clear them all.", "ja": "カウントダウンはもう不要なので、全部消して。"}, {"target": "all"}),
    ("cancel_timer", "cancel_not_alarm", {"ko": "알람 말고 주방 타이머만 취소해 줘.", "en": "Cancel the kitchen timer, not my alarm.", "ja": "アラームではなく、キッチンタイマーだけキャンセルして。"}, {"label": "kitchen"}),
    ("launch_app", "launch_editor", {"ko": "Visual Studio Code 실행해 줘.", "en": "Open Visual Studio Code for me.", "ja": "Visual Studio Codeを起動して。"}, {"application": "Visual Studio Code"}),
    ("launch_app", "launch_calculator", {"ko": "계산기 앱 띄워 줘.", "en": "Bring up the Calculator app.", "ja": "電卓アプリを開いて。"}, {"application": "Calculator"}),
    ("launch_app", "launch_notepad", {"ko": "메모장 열어 줄래?", "en": "Could you launch Notepad?", "ja": "メモ帳を開いてもらえる？"}, {"application": "Notepad"}),
    ("launch_app", "launch_browser", {"ko": "크롬 브라우저 시작해 줘.", "en": "Start the Chrome browser.", "ja": "Chromeブラウザーを起動して。"}, {"application": "Chrome"}),
    ("launch_app", "launch_paint", {"ko": "그림판 실행해.", "en": "Launch Paint.", "ja": "ペイントを起動して。"}, {"application": "Paint"}),
    ("launch_app", "launch_settings", {"ko": "윈도우 설정 창 열어 줘.", "en": "Open the Windows Settings window.", "ja": "Windowsの設定画面を開いて。"}, {"application": "Settings"}),
    ("launch_app", "launch_terminal", {"ko": "터미널 하나 실행해 줘.", "en": "Open a terminal window.", "ja": "ターミナルを一つ起動して。"}, {"application": "Terminal"}),
    ("launch_app", "launch_excel", {"ko": "엑셀 켜 줘.", "en": "Start Excel.", "ja": "Excelを起動して。"}, {"application": "Excel"}),
    ("launch_app", "launch_word", {"ko": "Word에서 새 문서를 쓰게 프로그램 열어 줘.", "en": "Open Word so I can write a new document.", "ja": "新しい文書を書くためにWordを開いて。"}, {"application": "Word"}),
    ("launch_app", "launch_discord", {"ko": "디스코드 실행해 줘.", "en": "Launch Discord.", "ja": "Discordを起動して。"}, {"application": "Discord"}),
    ("launch_app", "launch_task_manager", {"ko": "작업 관리자 띄워 줘.", "en": "Bring up Task Manager.", "ja": "タスクマネージャーを開いて。"}, {"application": "Task Manager"}),
    ("launch_app", "launch_file_explorer", {"ko": "파일 탐색기 열어 줘.", "en": "Open File Explorer.", "ja": "エクスプローラーを開いて。"}, {"application": "File Explorer"}),
)

COLLOQUIAL_STT = (
    ("get_current_time", "time_short_ko", {"ko": "지금 몇 시더라?", "en": "Time check—what time is it?", "ja": "今何時だっけ？"}, {"timezone": "local"}, "colloquial"),
    ("get_current_time", "time_filler_ko", {"ko": "저기, 지금 시각 좀 알려 줄래?", "en": "Hey, can you tell me the time now?", "ja": "えっと、今の時刻を教えてくれる？"}, {"timezone": "local"}, "colloquial"),
    ("get_current_time", "time_contracted", {"ko": "현재 몇 시인지 말해 줘", "en": "What's the time right now", "ja": "今の時間を教えて"}, {"timezone": "local"}, "stt_candidate"),
    ("get_current_time", "time_asr_typo", {"ko": "지금 시감 알려줘", "en": "Tell me the currant time", "ja": "今何時かおしえて"}, {"timezone": "local"}, "stt_candidate"),
    ("get_current_time", "time_casual", {"ko": "시간 확인 좀", "en": "What time do we have?", "ja": "今の時間、ちょっと確認してくれる？"}, {"timezone": "local"}, "colloquial"),
    ("get_current_time", "time_brief", {"ko": "시계 좀 봐 줘", "en": "Quick time check, please.", "ja": "時刻をちょっと確認して。"}, {"timezone": "local"}, "colloquial"),
    ("get_running_apps", "apps_short", {"ko": "지금 켜진 앱 뭐 있어?", "en": "What apps are open right now?", "ja": "今開いてるアプリは何？"}, {"scope": "all_running_applications"}, "colloquial"),
    ("get_running_apps", "apps_list_casual", {"ko": "실행 중인 프로그램들 쭉 보여 줘", "en": "Show me what's running.", "ja": "動いてるアプリを一覧で見せて。"}, {"scope": "all_running_applications"}, "colloquial"),
    ("get_running_apps", "apps_filler", {"ko": "어, 지금 백그라운드에 뭐 돌아가?", "en": "Um, what is running in the background?", "ja": "あの、バックグラウンドで何が動いてる？"}, {"scope": "all_running_applications"}, "colloquial"),
    ("get_running_apps", "apps_asr_typo", {"ko": "지금 실행중인 앱 목로 ㄱ보여줘", "en": "List the apps that are runing", "ja": "今起動中のアプリをいちらんにして"}, {"scope": "all_running_applications"}, "stt_candidate"),
    ("get_running_apps", "apps_which_active", {"ko": "현재 활성 앱 목록 부탁해", "en": "Which programs are active at the moment?", "ja": "現在アクティブなアプリを一覧にして。"}, {"scope": "all_running_applications"}, "colloquial"),
    ("get_running_apps", "apps_quick", {"ko": "컴퓨터에서 열린 거 확인해 줘", "en": "Check what I've got open.", "ja": "パソコンで開いているものを確認して。"}, {"scope": "all_running_applications"}, "colloquial"),
    ("take_screenshot", "screen_snap", {"ko": "화면 한 장 찍어 줘", "en": "Grab a screenshot for me.", "ja": "画面を一枚撮って。"}, {"target": "current_display"}, "colloquial"),
    ("take_screenshot", "screen_filler", {"ko": "저기, 지금 화면 캡처 좀 해 줄래?", "en": "Hey, could you capture my screen now?", "ja": "あの、今の画面をキャプチャしてくれる？"}, {"target": "current_display"}, "colloquial"),
    ("take_screenshot", "screen_save", {"ko": "현재 화면 스샷 저장해 줘", "en": "Save a shot of the screen as it is.", "ja": "今の画面のスクショを保存して。"}, {"target": "current_display"}, "colloquial"),
    ("take_screenshot", "screen_asr_typo", {"ko": "화면 캡쳐해서 남겨 줘", "en": "Take a screan capture", "ja": "画面をキャプチャして残して"}, {"target": "current_display"}, "stt_candidate"),
    ("take_screenshot", "screen_desktop", {"ko": "바탕화면 지금 모습 찍어 놔", "en": "Snap the desktop as it looks now.", "ja": "今のデスクトップを撮っておいて。"}, {"target": "current_display"}, "colloquial"),
    ("take_screenshot", "screen_quick", {"ko": "지금 화면 사진으로 남겨", "en": "Take a quick picture of what's on screen.", "ja": "今の画面を写真で残して。"}, {"target": "current_display"}, "colloquial"),
    ("adjust_volume", "volume_down_short", {"ko": "소리 좀 줄여 줘", "en": "Turn it down a little.", "ja": "音を少し下げて。"}, {"direction": "down", "amount_percent": 10}, "colloquial"),
    ("adjust_volume", "volume_up_short", {"ko": "볼륨 살짝 올려", "en": "Nudge the volume up.", "ja": "音量をちょっと上げて。"}, {"direction": "up", "amount_percent": 10}, "colloquial"),
    ("adjust_volume", "volume_filler", {"ko": "음, 스피커 소리 조금 낮춰 줘", "en": "Um, lower the speaker volume a bit.", "ja": "えっと、スピーカーの音量を少し下げて。"}, {"direction": "down", "amount_percent": 10}, "colloquial"),
    ("adjust_volume", "volume_asr_typo", {"ko": "음량 열로퍼센트 낮춰", "en": "Drop the volume by ten percent", "ja": "音量を10パーセント下げて"}, {"direction": "down", "amount_percent": 10}, "stt_candidate"),
    ("adjust_volume", "volume_numeric_casual", {"ko": "볼륨 15퍼만 올려 줘", "en": "Bump it up by fifteen percent.", "ja": "音量を15パーセントだけ上げて。"}, {"direction": "up", "amount_percent": 15}, "colloquial"),
    ("adjust_volume", "volume_output", {"ko": "오디오 출력 좀만 낮춰", "en": "Ease the audio output down a notch.", "ja": "音声出力を少しだけ下げて。"}, {"direction": "down", "amount_percent": 10}, "colloquial"),
)

# 안전 라벨은 UNKNOWN/fallback이다. candidate_tool은 가장 가까운 Tier A 혼동 대상만
# 기록하며 그 도구의 실행을 허용하지 않는다.
HARD_NEGATIVES = (
    ("volume_reason_01", "adjust_volume", "volume_meaning", {"ko": "소리가 너무 큰데 왜 그런지 설명해 줘.", "en": "The sound is too loud; explain why that might be.", "ja": "音が大きすぎるのはなぜか説明して。"}),
    ("volume_reason_02", "adjust_volume", "volume_meaning", {"ko": "알림음이 음악보다 크게 들리는 이유가 뭘까?", "en": "Why do notifications sound louder than the music?", "ja": "通知音が音楽より大きく聞こえるのはなぜ？"}),
    ("volume_advice_01", "adjust_volume", "volume_meaning", {"ko": "회의 전에 음량을 낮추는 게 좋을지 조언해 줘.", "en": "Advise me whether lowering the volume before the meeting would help.", "ja": "会議の前に音量を下げたほうがよいか相談したい。"}),
    ("volume_advice_02", "adjust_volume", "volume_meaning", {"ko": "녹음이 찢어지지 않게 볼륨을 어떻게 설정할지 알려줘.", "en": "How should I set the volume so the recording does not clip?", "ja": "録音が音割れしないように、音量をどう設定すればいい？"}),
    ("volume_translation_01", "adjust_volume", "volume_meaning", {"ko": "'볼륨을 높이지 마'를 영어로 번역해 줘.", "en": "Translate “don't turn up the volume” into Japanese.", "ja": "「音量を上げないで」を韓国語に訳して。"}),
    ("volume_negation_01", "adjust_volume", "volume_negation", {"ko": "볼륨 올리지 마. 지금 그대로 둬.", "en": "Do not turn the volume up; leave it as it is.", "ja": "音量を上げないで。今のままにして。"}),
    ("volume_negation_02", "adjust_volume", "volume_negation", {"ko": "소리 낮추지 말고 먼저 현재 설정이 뭔지 설명해 줘.", "en": "Don't lower the sound; first explain what the current setting means.", "ja": "音を下げずに、まず現在の設定の意味を説明して。"}),
    ("volume_negation_03", "adjust_volume", "volume_negation", {"ko": "음량을 20퍼센트 높이라는 말은 취소할게.", "en": "Cancel what I said about raising the volume by twenty percent.", "ja": "音量を20パーセント上げるという指示は取り消す。"}),
    ("volume_conditional_01", "adjust_volume", "volume_meaning", {"ko": "녹음이 끝나면 음량을 낮춰야 할지 다시 물어봐.", "en": "After the recording ends, ask me whether I want the volume lowered.", "ja": "録音が終わったら音量を下げるか、もう一度聞いて。"}),
    ("volume_past_01", "adjust_volume", "volume_meaning", {"ko": "어제 볼륨을 올린 건 나였는지 확인해 줘.", "en": "Check whether I was the one who raised the volume yesterday.", "ja": "昨日音量を上げたのが私だったか確認して。"}),
    ("volume_other_device", "adjust_volume", "volume_meaning", {"ko": "휴대폰에서 미디어 음량 줄이는 방법 알려줘.", "en": "Tell me how to lower media volume on a phone.", "ja": "スマートフォンでメディア音量を下げる方法を教えて。"}),
    ("volume_quote", "adjust_volume", "volume_meaning", {"ko": "화면에 '음량을 낮추세요'라고 쓰여 있어. 무슨 뜻이야?", "en": "The display says “reduce the volume”; what does that mean?", "ja": "画面に「音量を下げて」とあるけど、どういう意味？"}),
    ("volume_question_01", "adjust_volume", "volume_meaning", {"ko": "볼륨을 낮추면 배경 잡음도 작아져?", "en": "Would lowering the volume also make the background noise quieter?", "ja": "音量を下げると、背景ノイズも小さくなる？"}),
    ("volume_question_02", "adjust_volume", "volume_meaning", {"ko": "이어폰을 꽂았는데도 소리가 안 나. 어디부터 확인하지?", "en": "I plugged in headphones but hear nothing; what should I check first?", "ja": "ヘッドホンをつないでも音が出ない。まず何を確認すればいい？"}),
    ("volume_opinion", "adjust_volume", "volume_meaning", {"ko": "이 영상 배경음이 너무 큰 것 같아?", "en": "Do you think the background audio in this video is too loud?", "ja": "この動画のBGMは大きすぎると思う？"}),
    ("volume_deferred", "adjust_volume", "volume_meaning", {"ko": "다음 회의 시작할 때 음량을 낮추라는 메모를 작성해 줘.", "en": "Write a note reminding me to lower the volume when the next meeting starts.", "ja": "次の会議が始まったら音量を下げるよう、メモを書いて。"}),
    ("volume_explain_phrase", "adjust_volume", "volume_meaning", {"ko": "'소리를 조금 키워'라는 표현을 더 공손하게 바꿔 줘.", "en": "Make “turn it up a little” sound more polite.", "ja": "「音を少し上げて」をもっと丁寧な表現にして。"}),
    ("volume_comparison", "adjust_volume", "volume_meaning", {"ko": "스피커 음량과 마이크 입력 레벨은 어떻게 달라?", "en": "How is speaker volume different from microphone input gain?", "ja": "スピーカーの音量とマイク入力レベルはどう違う？"}),
    ("volume_hypothetical", "adjust_volume", "volume_meaning", {"ko": "볼륨을 절반으로 낮추면 배터리가 더 오래 갈까?", "en": "Would the battery last longer if I cut the volume in half?", "ja": "音量を半分にすれば、バッテリーは長持ちする？"}),
    ("volume_report", "adjust_volume", "volume_meaning", {"ko": "음량을 크게 올렸던 시각이 기록에 남아 있는지 찾아줘.", "en": "Find out whether the log records when the volume was turned up.", "ja": "音量を大きくした時刻がログに残っているか調べて。"}),

    ("time_availability_01", "get_current_time", "time_meaning", {"ko": "이번 주에 언제 시간이 괜찮아?", "en": "What time works for you this week?", "ja": "今週は何時ごろ都合がいい？"}),
    ("time_availability_02", "get_current_time", "time_meaning", {"ko": "금요일 회의는 몇 시로 잡는 게 좋을까?", "en": "What time should we schedule Friday's meeting?", "ja": "金曜日の会議は何時に設定するのがよさそう？"}),
    ("time_duration_01", "get_current_time", "time_meaning", {"ko": "시간 좀 내줄 수 있어? 상의할 게 있어.", "en": "Could you make some time for me? I have something to discuss.", "ja": "少し時間を取ってもらえる？相談したいことがある。"}),
    ("time_schedule_01", "get_current_time", "time_meaning", {"ko": "도서관 오늘 몇 시에 문 닫아?", "en": "What time does the library close today?", "ja": "図書館は今日何時に閉まる？"}),
    ("time_schedule_02", "get_current_time", "time_meaning", {"ko": "기차가 몇 시에 도착하는지 찾아봐 줘.", "en": "Look up what time the train arrives.", "ja": "電車が何時に到着するか調べて。"}),
    ("time_zone_01", "get_current_time", "time_meaning", {"ko": "서울이 오전 9시면 도쿄는 몇 시야?", "en": "If it's nine in Seoul, what time is it in Tokyo?", "ja": "ソウルが午前9時なら、東京は何時？"}),
    ("time_past_01", "get_current_time", "time_meaning", {"ko": "어제 회의가 몇 시에 시작했는지 회의록에서 확인해 줘.", "en": "Check the minutes to see what time yesterday's meeting started.", "ja": "議事録で、昨日の会議が何時に始まったか確認して。"}),
    ("time_duration_02", "get_current_time", "time_meaning", {"ko": "마감까지 몇 시간 남았는지 계산해 줘.", "en": "Calculate how many hours are left until the deadline.", "ja": "締め切りまであと何時間あるか計算して。"}),
    ("time_reminder_01", "get_current_time", "time_meaning", {"ko": "4시에 회의가 있다고 알림을 설정해 줘.", "en": "Set a reminder that I have a meeting at four.", "ja": "4時に会議があるとリマインドを設定して。"}),
    ("time_idiom_01", "get_current_time", "time_meaning", {"ko": "잠깐 시간 괜찮아? 질문 하나만 할게.", "en": "Do you have a minute? I have one question.", "ja": "ちょっと時間ある？一つ質問したい。"}),
    ("time_calendar_01", "get_current_time", "time_meaning", {"ko": "내일 일정표에 비어 있는 시간대가 있는지 찾아줘.", "en": "Find an open time slot in my calendar tomorrow.", "ja": "明日の予定表に空いている時間があるか探して。"}),
    ("time_future_01", "get_current_time", "time_meaning", {"ko": "다음 달 발표가 시작되는 시각을 알려줘.", "en": "Tell me what time next month's presentation begins.", "ja": "来月の発表が何時に始まるか教えて。"}),
    ("time_weather_01", "get_current_time", "time_meaning", {"ko": "해가 몇 시에 지는지 확인해 줘.", "en": "Find out what time the sun sets.", "ja": "日没が何時か調べて。"}),
    ("time_elapsed_01", "get_current_time", "time_meaning", {"ko": "우리가 시작한 지 얼마나 지났어?", "en": "How long has it been since we started?", "ja": "始めてからどれくらい経った？"}),
    ("time_quote_01", "get_current_time", "time_meaning", {"ko": "이 문장에서 '시간을 벌다'가 무슨 뜻인지 설명해 줘.", "en": "Explain what “buy some time” means in this sentence.", "ja": "この文の「時間を稼ぐ」という表現の意味を説明して。"}),
    ("time_future_plan", "get_current_time", "time_meaning", {"ko": "오후 세 시로 고객 미팅을 등록해 줘.", "en": "Put the customer meeting on my calendar for 3 p.m.", "ja": "顧客との打ち合わせを午後3時で予定に登録して。"}),
    ("time_deadline", "get_current_time", "time_meaning", {"ko": "보고서 마감 시간을 금요일 정오로 바꿔 줘.", "en": "Change the report deadline to noon on Friday.", "ja": "報告書の締め切りを金曜日の正午に変更して。"}),
    ("time_opinion", "get_current_time", "time_meaning", {"ko": "오후 회의는 너무 늦은 시간 같아?", "en": "Does an afternoon meeting seem too late to you?", "ja": "午後の会議は遅すぎる時間だと思う？"}),
    ("time_story", "get_current_time", "time_meaning", {"ko": "소설 속 시계가 8시를 가리키는 장면을 찾아줘.", "en": "Find the scene in the novel where the clock reads eight.", "ja": "小説の中で時計が8時を示す場面を探して。"}),
    ("time_meeting_duration", "get_current_time", "time_meaning", {"ko": "회의가 몇 분 걸렸는지 기록에서 계산해 줘.", "en": "Calculate from the notes how many minutes the meeting lasted.", "ja": "記録から会議に何分かかったか計算して。"}),

    ("screen_analyze_01", "take_screenshot", "screen_analysis", {"ko": "지금 화면에 뜬 오류 원인을 분석해 줘.", "en": "Analyze the error currently shown on screen.", "ja": "今画面に出ているエラーの原因を分析して。"}),
    ("screen_read_01", "take_screenshot", "screen_analysis", {"ko": "현재 화면에 표시된 코드를 읽고 설명해 줘.", "en": "Read and explain the code displayed on the screen.", "ja": "画面に表示されているコードを読んで説明して。"}),
    ("screen_share_01", "take_screenshot", "screen_share", {"ko": "방금 찍은 스크린샷을 팀 채팅방에 보내 줘.", "en": "Send the screenshot I just took to the team chat.", "ja": "さっき撮ったスクリーンショットをチームチャットに送って。"}),
    ("screen_compare_01", "take_screenshot", "screen_analysis", {"ko": "이 두 스크린샷에서 달라진 부분을 비교해 줘.", "en": "Compare these two screenshots and point out what changed.", "ja": "この2枚のスクリーンショットを比べて、変わったところを教えて。"}),
    ("screen_past_01", "take_screenshot", "screen_analysis", {"ko": "어제 저장한 화면 캡처에서 파일 이름을 찾아줘.", "en": "Find the filename in the screen capture I saved yesterday.", "ja": "昨日保存した画面キャプチャからファイル名を探して。"}),
    ("screen_howto_01", "take_screenshot", "screen_howto", {"ko": "윈도우에서 스크린샷 찍는 방법을 알려줘.", "en": "Explain how to take a screenshot in Windows.", "ja": "Windowsでスクリーンショットを撮る方法を教えて。"}),
    ("screen_video_01", "take_screenshot", "screen_analysis", {"ko": "화면을 사진 말고 동영상으로 녹화해 줘.", "en": "Record the screen as a video instead of taking a still image.", "ja": "静止画ではなく、画面を動画として録画して。"}),
    ("screen_where_01", "take_screenshot", "screen_analysis", {"ko": "캡처한 이미지가 어느 폴더에 저장됐는지 알려줘.", "en": "Tell me which folder contains the image I captured.", "ja": "キャプチャした画像がどのフォルダーに保存されたか教えて。"}),
    ("screen_negation_01", "take_screenshot", "screen_analysis", {"ko": "스크린샷 찍지 말고 지금 보이는 팝업 문구만 설명해 줘.", "en": "Don't take a screenshot; just explain the popup text I can see.", "ja": "スクリーンショットは撮らず、見えているポップアップの文言だけ説明して。"}),
    ("screen_edit_01", "take_screenshot", "screen_analysis", {"ko": "스크린샷에서 이메일 주소를 흐리게 처리해 줘.", "en": "Blur the email address in this screenshot.", "ja": "このスクリーンショットのメールアドレスをぼかして。"}),
    ("screen_review_01", "take_screenshot", "screen_analysis", {"ko": "지난주 캡처와 지금 화면을 비교해서 차이를 정리해 줘.", "en": "Compare last week's capture with the current screen and summarize the differences.", "ja": "先週のキャプチャと今の画面を比べて、違いをまとめて。"}),
    ("screen_send_02", "take_screenshot", "screen_share", {"ko": "스크린샷을 저장한 다음 외부 업체에 공유해 줘.", "en": "Save the screenshot and then share it with the vendor.", "ja": "スクリーンショットを保存してから、取引先と共有して。"}),
    ("screen_explain_icon", "take_screenshot", "screen_analysis", {"ko": "화면 오른쪽 위에 있는 아이콘이 무슨 역할인지 알려줘.", "en": "Tell me what the icon in the upper-right corner of the screen does.", "ja": "画面の右上にあるアイコンの役割を教えて。"}),
    ("screen_count", "take_screenshot", "screen_analysis", {"ko": "공유 폴더에 저장된 스크린샷이 몇 장인지 세어 줘.", "en": "Count how many screenshots are in the shared folder.", "ja": "共有フォルダーにスクリーンショットが何枚あるか数えて。"}),
    ("screen_security", "take_screenshot", "screen_analysis", {"ko": "화면 캡처에 비밀번호가 노출됐는지 검사해 줘.", "en": "Check whether the screen capture exposes a password.", "ja": "画面キャプチャにパスワードが写り込んでいないか確認して。"}),
    ("screen_crop", "take_screenshot", "screen_analysis", {"ko": "이 스크린샷에서 대화창 부분만 잘라 줘.", "en": "Crop this screenshot to show only the chat window.", "ja": "このスクリーンショットからチャット画面だけ切り抜いて。"}),
    ("screen_translate", "take_screenshot", "screen_analysis", {"ko": "스크린샷에 나온 일본어 문장을 번역해 줘.", "en": "Translate the Japanese sentence in this screenshot.", "ja": "スクリーンショットにある韓国語の文を翻訳して。"}),
    ("screen_permission", "take_screenshot", "screen_share", {"ko": "이 화면을 고객에게 보내도 되는지 개인정보가 있는지 확인해 줘.", "en": "Check this screen for personal information before I send it to the customer.", "ja": "顧客に送る前に、この画面に個人情報がないか確認して。"}),
    ("screen_tutorial", "take_screenshot", "screen_analysis", {"ko": "스크린샷을 찍는 단축키가 뭔지 알려줘.", "en": "What keyboard shortcut takes a screenshot?", "ja": "スクリーンショットを撮るショートカットキーは何？"}),
    ("screen_modal", "take_screenshot", "screen_analysis", {"ko": "팝업창을 닫지 말고 안에 적힌 안내를 읽어 줘.", "en": "Leave the popup open and read the instructions inside it.", "ja": "ポップアップを閉じずに、中の案内を読んで。"}),

    ("apps_close_all", "get_running_apps", "app_side_effect", {"ko": "열려 있는 앱을 전부 닫아 줘.", "en": "Close every application that's open.", "ja": "開いているアプリを全部閉じて。"}),
    ("apps_close_chrome", "get_running_apps", "app_side_effect", {"ko": "크롬 창만 종료해 줘.", "en": "Close just the Chrome window.", "ja": "Chromeのウィンドウだけ閉じて。"}),
    ("apps_stop_process", "get_running_apps", "app_side_effect", {"ko": "응답 없는 프로그램 프로세스를 강제로 끝내 줘.", "en": "Force-quit the unresponsive application process.", "ja": "応答していないアプリのプロセスを強制終了して。"}),
    ("apps_resource_question", "get_running_apps", "app_diagnosis", {"ko": "어떤 앱이 CPU를 가장 많이 쓰는지 원인을 분석해 줘.", "en": "Diagnose which app is using the most CPU and why.", "ja": "どのアプリがCPUを最も使っているか、原因も含めて診断して。"}),
    ("apps_launch_chrome", "get_running_apps", "app_launch", {"ko": "크롬이 안 보이는데 새 창을 열어 줘.", "en": "I can't see Chrome; open a new window for me.", "ja": "Chromeが見当たらないので、新しいウィンドウを開いて。"}),
    ("apps_close_except", "get_running_apps", "app_side_effect", {"ko": "문서 편집기만 남기고 나머지 앱은 다 종료해 줘.", "en": "Quit every app except the document editor.", "ja": "文書エディター以外のアプリをすべて終了して。"}),
    ("apps_restart", "get_running_apps", "app_side_effect", {"ko": "브라우저가 멈추면 종료했다가 다시 실행해 줘.", "en": "If the browser is frozen, close it and relaunch it.", "ja": "ブラウザーが固まっていたら終了して、もう一度起動して。"}),
    ("apps_disable_startup", "get_running_apps", "app_settings", {"ko": "부팅할 때 자동으로 실행되는 앱을 꺼 줘.", "en": "Disable the apps that start automatically at boot.", "ja": "起動時に自動で立ち上がるアプリを無効にして。"}),
    ("apps_remove", "get_running_apps", "app_settings", {"ko": "사용하지 않는 프로그램을 컴퓨터에서 삭제해 줘.", "en": "Uninstall the programs I no longer use.", "ja": "使っていないプログラムをパソコンから削除して。"}),
    ("apps_close_background", "get_running_apps", "app_side_effect", {"ko": "백그라운드에서 도는 앱들을 모두 멈춰 줘.", "en": "Stop all the apps running in the background.", "ja": "バックグラウンドで動いているアプリを全部止めて。"}),
    ("apps_access_question", "get_running_apps", "app_diagnosis", {"ko": "내 계정에서 이 프로그램을 실행할 권한이 있는지 확인해 줘.", "en": "Check whether my account is allowed to run this program.", "ja": "自分のアカウントでこのプログラムを実行できるか確認して。"}),
    ("apps_hide", "get_running_apps", "app_side_effect", {"ko": "현재 창들을 작업 표시줄에서 숨겨 줘.", "en": "Hide the current windows from the taskbar.", "ja": "今開いているウィンドウをタスクバーから隠して。"}),
    ("apps_permission", "get_running_apps", "app_settings", {"ko": "이 앱이 마이크를 사용하지 못하게 권한을 바꿔 줘.", "en": "Change the permissions so this app cannot use the microphone.", "ja": "このアプリがマイクを使えないように権限を変更して。"}),
    ("apps_update", "get_running_apps", "app_settings", {"ko": "열려 있는 프로그램들을 최신 버전으로 업데이트해 줘.", "en": "Update the open programs to their latest versions.", "ja": "開いているプログラムを最新バージョンに更新して。"}),
    ("apps_close_save", "get_running_apps", "app_side_effect", {"ko": "저장하지 않은 내용은 버리고 앱을 닫아 줘.", "en": "Discard unsaved changes and close the app.", "ja": "未保存の変更を破棄して、アプリを閉じて。"}),
    ("apps_startup_list", "get_running_apps", "app_settings", {"ko": "윈도우 시작 프로그램에서 메신저를 빼 줘.", "en": "Remove the messenger from the Windows startup list.", "ja": "Windowsのスタートアップ一覧からメッセンジャーを外して。"}),
    ("apps_close_confirm", "get_running_apps", "app_side_effect", {"ko": "실행 중인 앱을 모두 닫아도 되는지 먼저 물어봐.", "en": "Ask me first whether it's okay to close the running apps.", "ja": "実行中のアプリを閉じてよいか、先に私に確認して。"}),
    ("apps_cpu_limit", "get_running_apps", "app_settings", {"ko": "게임이 CPU를 덜 쓰도록 설정을 바꿔 줘.", "en": "Change the settings so the game uses less CPU.", "ja": "ゲームがCPUを使いすぎないよう設定を変更して。"}),
    ("apps_switch", "get_running_apps", "app_side_effect", {"ko": "현재 쓰던 앱에서 메모장으로 전환해 줘.", "en": "Switch from the app I'm using to Notepad.", "ja": "今使っているアプリからメモ帳に切り替えて。"}),
    ("apps_security_scan", "get_running_apps", "app_diagnosis", {"ko": "실행 중인 프로그램에서 의심스러운 동작이 있는지 검사해 줘.", "en": "Scan the running programs for suspicious behavior.", "ja": "実行中のプログラムに不審な動作がないか調べて。"}),

    ("multi_time_volume", "get_current_time", "multi_intent", {"ko": "지금 몇 시인지 알려 주고 볼륨도 낮춰 줘.", "en": "Tell me the current time and lower the volume too.", "ja": "今何時か教えて、音量も下げて。"}),
    ("multi_screen_email", "take_screenshot", "multi_intent", {"ko": "화면을 캡처해서 팀에 이메일로 보내 줘.", "en": "Capture the screen and email it to the team.", "ja": "画面をキャプチャして、チームにメールで送って。"}),
    ("multi_apps_close", "get_running_apps", "multi_intent", {"ko": "열려 있는 앱 목록을 보여 주고 전부 닫아 줘.", "en": "List the open apps and then close them all.", "ja": "開いているアプリを一覧にしてから、全部閉じて。"}),
    ("multi_volume_launch", "adjust_volume", "multi_intent", {"ko": "음량을 높이고 크롬도 실행해 줘.", "en": "Raise the volume and launch Chrome as well.", "ja": "音量を上げて、Chromeも起動して。"}),
    ("multi_time_apps", "get_current_time", "multi_intent", {"ko": "현재 시각이랑 실행 중인 앱 목록 둘 다 알려줘.", "en": "Give me both the current time and a list of running apps.", "ja": "現在時刻と実行中のアプリ一覧を両方教えて。"}),
    ("multi_timer_screenshot", "take_screenshot", "multi_intent", {"ko": "스크린샷을 찍고 10분 타이머도 설정해 줘.", "en": "Take a screenshot and set a ten-minute timer.", "ja": "スクリーンショットを撮って、10分のタイマーも設定して。"}),
    ("multi_weather_volume", "adjust_volume", "multi_intent", {"ko": "서울 날씨 확인하고 스피커 소리도 줄여 줘.", "en": "Check the weather in Seoul and turn down the speakers.", "ja": "ソウルの天気を調べて、スピーカーの音量も下げて。"}),
    ("multi_launch_timer", "get_running_apps", "multi_intent", {"ko": "계산기를 열고 5분 타이머를 시작해 줘.", "en": "Open Calculator and start a five-minute timer.", "ja": "電卓を開いて、5分のタイマーを始めて。"}),
    ("multi_apps_capture", "get_running_apps", "multi_intent", {"ko": "현재 앱을 나열한 다음 화면을 캡처해 줘.", "en": "List the active apps, then capture the screen.", "ja": "現在のアプリを一覧にしてから、画面をキャプチャして。"}),
    ("multi_capture_explain", "take_screenshot", "multi_intent", {"ko": "화면을 캡처하고 거기에 나온 오류도 설명해 줘.", "en": "Capture the screen and explain the error shown in it.", "ja": "画面をキャプチャして、そこに表示されたエラーも説明して。"}),
    ("multi_conditional_volume", "adjust_volume", "multi_intent", {"ko": "녹음이 찢어질 것 같으면 음량을 낮춰 줘.", "en": "Lower the volume if the recording looks like it will clip.", "ja": "録音が音割れしそうなら、音量を下げて。"}),
    ("multi_conditional_apps", "get_running_apps", "multi_intent", {"ko": "크롬이 실행 중이 아니면 열고, 실행 중이면 목록만 보여 줘.", "en": "If Chrome isn't running, open it; otherwise just show me the list.", "ja": "Chromeが起動していなければ開き、起動中なら一覧だけ見せて。"}),
    ("multi_future_close", "get_running_apps", "multi_intent", {"ko": "저녁 6시에 실행 중인 프로그램을 전부 종료해 줘.", "en": "At six this evening, close every program that's running.", "ja": "今夜6時に実行中のプログラムを全部終了して。"}),
    ("multi_volume_reason", "adjust_volume", "multi_intent", {"ko": "소리를 줄이고 왜 컸는지도 알려줘.", "en": "Turn the sound down and tell me why it was loud.", "ja": "音を下げて、なぜ大きかったのかも教えて。"}),
    ("multi_screenshot_share", "take_screenshot", "multi_intent", {"ko": "화면 캡처해서 공유 폴더에 저장해 줘.", "en": "Capture the screen and save it in the shared folder.", "ja": "画面をキャプチャして、共有フォルダーに保存して。"}),
    ("multi_apps_diagnose", "get_running_apps", "multi_intent", {"ko": "열려 있는 앱을 확인하고 컴퓨터가 느린 이유도 찾아줘.", "en": "Check which apps are open and diagnose why the computer is slow.", "ja": "開いているアプリを確認して、パソコンが遅い理由も調べて。"}),
    ("multi_weather_timer", "get_current_time", "multi_intent", {"ko": "내일 날씨를 확인하고 그때 알림 타이머를 설정해 줘.", "en": "Check tomorrow's weather and set a reminder timer for then.", "ja": "明日の天気を調べて、その時間に知らせるタイマーを設定して。"}),
    ("multi_screen_close", "take_screenshot", "multi_intent", {"ko": "화면에 오류가 있는지 확인한 뒤 팝업을 닫아 줘.", "en": "Check the screen for an error and then close the popup.", "ja": "画面にエラーがないか確認してから、ポップアップを閉じて。"}),
    ("multi_time_schedule", "get_current_time", "multi_intent", {"ko": "현재 시간 알려 주고 오후 4시에 회의를 등록해 줘.", "en": "Tell me the current time and schedule a meeting for four p.m.", "ja": "現在時刻を教えて、午後4時に会議を登録して。"}),
    ("multi_timer_cancel", "get_running_apps", "multi_intent", {"ko": "새 타이머를 설정하고 전에 걸어 둔 타이머는 취소해 줘.", "en": "Set a new timer and cancel the one I started earlier.", "ja": "新しいタイマーを設定して、前にかけたものはキャンセルして。"}),
)
